import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

const helveticaCompressed = localFont({
    src: "../../public/fonts/helvetica-compressed.woff2",
    display: "swap",
    variable: "--font-helvetica-compressed",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn(helveticaCompressed.variable)}>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
